name: Playwright Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-smoke-and-regression-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Project Dependencies
        run: npm install
      
      - name: Install Concurrently
        run: npm install concurrently cross-env --save-dev
      
      - name: Run Smoke Tests on QA
        run: npm run smoke:all:qa
      
      - name: Run Smoke Regression Tests
        run: npm run smoke-regression:all
      
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/